name: HOPR Test

on:
  push:
    branches: ['**']

jobs:
  build:
    name: Build & Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16]
        os: ['ubuntu-latest', 'macos-latest']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install

      - name: Test
        run: |
          yarn test