# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ["robertkiel/release-lifecycle"]

jobs:
  publish-npm:
    strategy:
      matrix:
        node-version: [16]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Yarn version
        run: |
            yarn version check
      # - name: Install dependencies
      #   run: |
      #     yarn install    

      # - name: Build
      #   run: |
      #     yarn build

      # - name: Publish to NPM
      #   run: |
      #     yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      #     yarn npm publish